# Generated by Django 3.2.16 on 2024-06-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emaillog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='user',
        ),
    ]
